### ISSUE TITLE
Documentation page says "python app_gradio.py", should be "python gradio_app.py"

### ISSUE THREAD

**Issue by J-o-h-n-M** [SongweiGe/rich-text-to-image#1]
Documentation page says "python app_gradio.py", should be "python gradio_app.py"

**Comment by SongweiGe** [comment]
Thank you for your interest and for pointing that out. I have [fixed the typo](https://github.com/SongweiGe/rich-text-to-image/commit/c5c4a30295ed7042d27da8efc0412bd2dfe5c410).
