### ISSUE TITLE
how to change the code to fit SDXL-lora？

### ISSUE THREAD

**Issue by ZhuangLii** [songweige/rich-text-to-image#14]
hello, thank you for your generous code
sharing. could you please help me to change the code to fit SDXl lora, thx

**Comment by songweige** [comment]
Hey @ZhuangLii, thanks for your interest! I create a [branch for the lora implementation](https://github.com/songweige/rich-text-to-image/tree/lora). Note that you need a slightly different environment for lora. After creating the environment with `conda env create -f environment.yaml`, you can launch the demo with `python gradio_app_lora_xl.py`.

**Comment by songweige** [comment]
Here is an example I tried with [this lora weight](https://huggingface.co/nerijs/pixel-art-xl). You may specify your own lora model by changing [here](https://github.com/songweige/rich-text-to-image/blob/b01631dfcba268dce6ab8496f2acbb9597cad296/gradio_app_lora_xl.py#L66).
<img width="737" alt="image" src="https://github.com/songweige/rich-text-to-image/assets/22885450/bb1f77b3-5c62-408a-9a53-02d78b3bcf63">

**Comment by ZhuangLii** [comment]
> Hey @ZhuangLii, thanks for your interest! I create a [branch for the lora implementation](https://github.com/songweige/rich-text-to-image/tree/lora). Note that you need a slightly different environment for lora. After creating the environment with `conda env create -f environment.yaml`, you can launch the demo with `python gradio_app_lora_xl.py`.


I can't believe you created a new branch for this issue. Your efficiency is greatly appreciated!

**Comment by songweige** [comment]
I happened to play around the lora models with this recently. : ) Feel free to reopen this if you run into any errors.
