### ISSUE TITLE
UnboundLocalError: local variable 'attn_probs' referenced before assignment

### ISSUE THREAD

**Issue by howardgriffin** [SongweiGe/rich-text-to-image#4]
How to solve this problem?

**Comment by SongweiGe** [comment]
Thanks for reporting this. The xformer option was inherited from the diffusers codebase. The current implementation does not support [xformer attention](https://github.com/SongweiGe/rich-text-to-image/blob/7780c3784e27aa803d6e5138807409e6d2973891/models/attention.py#L657)  as we need to manipulate [attention_probs](https://github.com/SongweiGe/rich-text-to-image/blob/7780c3784e27aa803d6e5138807409e6d2973891/models/attention.py#L633).
