### ISSUE TITLE
Train on a custom dataset?

### ISSUE THREAD

**Issue by alelordelo** [SongweiGe/rich-text-to-image#6]
Hi, thanks for the amazing paper and code! : )

Would it be possible to train a a custom dataset with segmentation maps and nested JSON prompts?

cheers

**Comment by SongweiGe** [comment]
Hi, thank you for your interest! Our method does not require any training. If you have another model, say stable diffusion finetuned on the custom dataset, you may directly load the model checkpoint and use our rich-text formats to control the generation.

**Comment by alelordelo** [comment]
thanks @SongweiGe
Great, will try to run with with a custom model!

Does it work with image to image as well? Would be super helpful to specify prompts per masked region

**Comment by SongweiGe** [comment]
For image-to-image models, I think it would be possible to integrate with models like ControlNet. I don't think it is compatible with models like InstructPix2Pix.

**Comment by alelordelo** [comment]
What about the default stable diffusion 1.5 image to image?Sent from my iPhoneOn 20 Apr 2023, at 05:41, SongweiGe ***@***.***> wrote:﻿
For image-to-image models, I think it would be possible to integrate with models like ControlNet. I don't think it is compatible with models like InstructPix2Pix.

**Comment by SongweiGe** [comment]
Sorry for missing your question. I think it is compatible with the SDEdit kind of method.
