### ISSUE TITLE
Image quality  decreased

### ISSUE THREAD

**Issue by howardgriffin** [SongweiGe/rich-text-to-image#7]
By trying your demo, I found the rich-texted image quality decreased obviously. Any suggestions?
I my case, I used the prompt {"ops":[{"insert":"a"},{"attributes":{"size":"32px"},"insert":" dog "},{"insert":"and a "},{"attributes":{"size":"32px"},"insert":"cat"},{"insert":"\n"}]}, other settings were the default.

**Comment by SongweiGe** [comment]
I got the following image with your json input. Is it the same as what you saw?  
![seed6_rich](https://user-images.githubusercontent.com/22885450/233252583-e22bc8e9-e6ce-4630-a8be-878b9a720310.png)

**Comment by howardgriffin** [comment]
Yes, this is the same situation as mine. This picture looks worse than the plain-text image.
