### ISSUE TITLE
cross-attention maps are not robust

### ISSUE THREAD

**Issue by jinxixiang** [SongweiGe/rich-text-to-image#9]
Thank you for sharing such an interesting idea. 

But I think one drawback of the demo, if I could be wrong, is the cross-attention maps are not robust.  The results could be corrupted.

<img width="1189" alt="badcase" src="https://user-images.githubusercontent.com/66879343/234279679-4e4af7e4-c141-4532-958b-f773d903f95e.PNG">

**Comment by jinxixiang** [comment]
<img width="1189" alt="badcase" src="https://user-images.githubusercontent.com/66879343/234455567-ae0aa218-fc63-4b1a-979c-0c9e4c223334.PNG">

**Comment by jinxixiang** [comment]
![hair](https://user-images.githubusercontent.com/66879343/234455837-293151b1-ba00-4743-8bbe-fd0976573b61.PNG)

**Comment by SongweiGe** [comment]
Hi @jinxixiang, thank you for your interest and for trying out our demo!

You are right that the token maps are sometimes not quite stable and accurate. We have been working on improving this and had some progress. Here is the example that changes the color of the hair.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/22885450/234675107-1a518de1-95f9-4899-b97d-0c6c5cb8244d.png">

**Comment by jinxixiang** [comment]
@SongweiGe Woo, this improved result is great! What did you modify with the cross-attention map? It seems to be refined.

I think one walkaround of this problem is utilizing the ability of [Gounding SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) by splitting the denoising process into two stages. The first stage is to get the region mask, and the second stage is to conduct region-based diffusion. We are working on it.

**Comment by SongweiGe** [comment]
We made a few changes. One major change was to use self-attention maps to compute the segmentation. Here are more examples. Hopefully we will update the demo by the end of this week.

![image](https://user-images.githubusercontent.com/22885450/234744903-55678291-1cc3-408c-aec7-ab18d85ef216.png)

Using SAM is a natural and nice idea. Please do let me know once you have some results or need any help from me.
